---
- name: Ensure that taps are tapped.
  homebrew_tap: 
    tap: "{{ item }}"
    state: "present"
    path: "{{ homebrew_prefix }}/bin"
  with_items:
  - "digitalspacestdio/nextgen-devenv"

- name: "Ensure digitalspace-supervisor"
  homebrew:
    name: "digitalspace-supervisor"
    state: latest

- name: "Ensure digitalspace-nginx"
  homebrew:
    name: "digitalspace-nginx"
    state: latest